if(NOT DEFINED LIB_DIR OR NOT DEFINED LIBS)
    message(FATAL_ERROR "LIB_DIR and LIBS must be set.")
endif()

file(GLOB _lib_candidates RELATIVE "${LIB_DIR}" "${LIB_DIR}/*.a")
foreach(_lib_name IN LISTS LIBS)
    set(_target "${LIB_DIR}/${_lib_name}.a")
    if(EXISTS "${_target}")
        continue()
    endif()
    file(GLOB _matches "${LIB_DIR}/${_lib_name}-*.a")
    list(SORT _matches)
    list(LENGTH _matches _match_count)
    if(_match_count EQUAL 0)
        continue()
    endif()
    list(GET _matches 0 _source)
    file(CREATE_LINK "${_source}" "${_target}" SYMBOLIC)
endforeach()
